import {
  Cohort,
  Track,
  Student,
  Instructor,
  ClassSession,
  Assignment,
  Submission,
  Announcement,
  Enrollment,
  ActivityItem,
} from "@/types";

export const mockCohorts: Cohort[] = [
  {
    id: "coh-2026-1",
    name: "DSA Bootcamp 2026",
    status: "Active",
    startDate: "Jan 15, 2026",
    endDate: "May 15, 2026",
    totalStudents: 84,
    tracksCount: 3,
  },
  {
    id: "coh-2025-2",
    name: "Full Stack Winter 2025",
    status: "Completed",
    startDate: "Sep 1, 2025",
    endDate: "Dec 20, 2025",
    totalStudents: 72,
    tracksCount: 2,
  },
];

export const mockTracks: Track[] = [
  {
    id: "trk-foundations",
    name: "Foundations",
    cohortId: "coh-2026-1",
    cohortName: "DSA Bootcamp 2026",
    description: "Core algorithms, Big-O analysis, Hash Maps, Strings, and Two-Pointers.",
    instructorName: "Marcus Vance",
    instructorEmail: "marcus@bootcamp.edu",
    studentsCount: 28,
    sessionsCount: 16,
    assignmentsCount: 8,
    schedule: "Mon / Wed • 6:00 PM EST",
  },
  {
    id: "trk-intermediate",
    name: "Intermediate",
    cohortId: "coh-2026-1",
    cohortName: "DSA Bootcamp 2026",
    description: "Sliding Window, Binary Search, Trees, Graphs, and Heap implementations.",
    instructorName: "Sarah Jenkins",
    instructorEmail: "sarah@bootcamp.edu",
    studentsCount: 32,
    sessionsCount: 16,
    assignmentsCount: 8,
    schedule: "Tue / Thu • 6:00 PM EST",
  },
  {
    id: "trk-advanced",
    name: "Advanced",
    cohortId: "coh-2026-1",
    cohortName: "DSA Bootcamp 2026",
    description: "Dynamic Programming, Graph Shortest Paths, Trie, and Hard LeetCode patterns.",
    instructorName: "Devon Reed",
    instructorEmail: "devon@bootcamp.edu",
    studentsCount: 24,
    sessionsCount: 16,
    assignmentsCount: 8,
    schedule: "Sat / Sun • 11:00 AM EST",
  },
];

export const mockInstructors: Instructor[] = [
  {
    id: "inst-001",
    name: "Sarah Jenkins",
    email: "sarah@bootcamp.edu",
    initials: "SJ",
    assignedTracks: ["Intermediate"],
    totalStudents: 32,
    activeSessions: 6,
    roleTitle: "Lead Algorithms Instructor",
  },
  {
    id: "inst-002",
    name: "Marcus Vance",
    email: "marcus@bootcamp.edu",
    initials: "MV",
    assignedTracks: ["Foundations"],
    totalStudents: 28,
    activeSessions: 5,
    roleTitle: "Staff Instructor",
  },
  {
    id: "inst-003",
    name: "Devon Reed",
    email: "devon@bootcamp.edu",
    initials: "DR",
    assignedTracks: ["Advanced"],
    totalStudents: 24,
    activeSessions: 5,
    roleTitle: "Senior Systems & Algorithms Coach",
  },
];

export const mockStudents: Student[] = [
  {
    id: "std-001",
    name: "Alex Morgan",
    email: "alex.morgan@bootcamp.edu",
    initials: "AM",
    trackId: "trk-intermediate",
    trackName: "Intermediate",
    cohortName: "DSA Bootcamp 2026",
    attendanceRate: 94,
    assignmentsCompleted: 6,
    totalAssignments: 8,
    averageScore: 92,
    status: "Active",
  },
  {
    id: "std-002",
    name: "Elena Rostova",
    email: "elena.r@bootcamp.edu",
    initials: "ER",
    trackId: "trk-intermediate",
    trackName: "Intermediate",
    cohortName: "DSA Bootcamp 2026",
    attendanceRate: 100,
    assignmentsCompleted: 8,
    totalAssignments: 8,
    averageScore: 98,
    status: "Active",
  },
  {
    id: "std-003",
    name: "Jordan Lee",
    email: "jordan.lee@bootcamp.edu",
    initials: "JL",
    trackId: "trk-intermediate",
    trackName: "Intermediate",
    cohortName: "DSA Bootcamp 2026",
    attendanceRate: 88,
    assignmentsCompleted: 5,
    totalAssignments: 8,
    averageScore: 84,
    status: "Active",
  },
  {
    id: "std-004",
    name: "Tariq Mansour",
    email: "tariq.m@bootcamp.edu",
    initials: "TM",
    trackId: "trk-foundations",
    trackName: "Foundations",
    cohortName: "DSA Bootcamp 2026",
    attendanceRate: 92,
    assignmentsCompleted: 6,
    totalAssignments: 8,
    averageScore: 89,
    status: "Active",
  },
  {
    id: "std-005",
    name: "Priya Sharma",
    email: "priya.s@bootcamp.edu",
    initials: "PS",
    trackId: "trk-foundations",
    trackName: "Foundations",
    cohortName: "DSA Bootcamp 2026",
    attendanceRate: 96,
    assignmentsCompleted: 7,
    totalAssignments: 8,
    averageScore: 95,
    status: "Active",
  },
  {
    id: "std-006",
    name: "Carlos Mendez",
    email: "carlos.m@bootcamp.edu",
    initials: "CM",
    trackId: "trk-advanced",
    trackName: "Advanced",
    cohortName: "DSA Bootcamp 2026",
    attendanceRate: 90,
    assignmentsCompleted: 7,
    totalAssignments: 8,
    averageScore: 91,
    status: "Active",
  },
  {
    id: "std-007",
    name: "Samantha Wright",
    email: "sam.wright@bootcamp.edu",
    initials: "SW",
    trackId: "trk-advanced",
    trackName: "Advanced",
    cohortName: "DSA Bootcamp 2026",
    attendanceRate: 75,
    assignmentsCompleted: 4,
    totalAssignments: 8,
    averageScore: 78,
    status: "At Risk",
  },
  {
    id: "std-008",
    name: "David Kim",
    email: "david.kim@bootcamp.edu",
    initials: "DK",
    trackId: "trk-intermediate",
    trackName: "Intermediate",
    cohortName: "DSA Bootcamp 2026",
    attendanceRate: 91,
    assignmentsCompleted: 6,
    totalAssignments: 8,
    averageScore: 87,
    status: "Active",
  },
];

export const mockSessions: ClassSession[] = [
  {
    id: "ses-101",
    title: "Sliding Window & Two-Pointer Strategies",
    track: "Intermediate",
    instructor: {
      name: "Sarah Jenkins",
      role: "Lead Instructor",
    },
    date: "Today, Mar 28",
    time: "6:00 PM – 8:00 PM EST",
    type: "Live Lecture",
    meetingUrl: "https://meet.google.com/abc-defg-hij",
    isNext: true,
  },
  {
    id: "ses-102",
    title: "Arrays & Hash Maps: Collision Resolution & Fast Lookups",
    track: "Foundations",
    instructor: {
      name: "Marcus Vance",
      role: "Staff Instructor",
    },
    date: "Tomorrow, Mar 29",
    time: "6:00 PM – 7:30 PM EST",
    type: "Workshop",
    meetingUrl: "https://meet.google.com/mno-pqrs-tuv",
  },
  {
    id: "ses-103",
    title: "Stacks & Queues: Monotonic Stacks in Depth",
    track: "Intermediate",
    instructor: {
      name: "Sarah Jenkins",
      role: "Lead Instructor",
    },
    date: "Monday, Mar 31",
    time: "6:00 PM – 8:00 PM EST",
    type: "Live Lecture",
    meetingUrl: "https://meet.google.com/wxy-zabc-def",
  },
  {
    id: "ses-104",
    title: "Dynamic Programming: Memoization vs Tabulation",
    track: "Advanced",
    instructor: {
      name: "Devon Reed",
      role: "Senior Coach",
    },
    date: "Saturday, Apr 4",
    time: "11:00 AM – 1:00 PM EST",
    type: "Live Lecture",
    meetingUrl: "https://meet.google.com/ghi-jklm-nop",
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: "asg-01",
    title: "Two Sum Practice & Frequency Arrays",
    track: "Foundations",
    dueDate: "Yesterday, Mar 27",
    status: "submitted",
    totalSubmissions: 28,
    gradedCount: 26,
    score: 95,
    maxScore: 100,
  },
  {
    id: "asg-02",
    title: "Sliding Window Exercise: Max Subarray & Min Window Substring",
    track: "Intermediate",
    dueDate: "Due in 2 days (Mar 30)",
    status: "in_progress",
    totalSubmissions: 18,
    gradedCount: 8,
    maxScore: 100,
  },
  {
    id: "asg-03",
    title: "Stack Problems: Valid Parentheses & Daily Temperatures",
    track: "Intermediate",
    dueDate: "Due Apr 4",
    status: "pending",
    totalSubmissions: 4,
    gradedCount: 0,
    maxScore: 100,
  },
  {
    id: "asg-04",
    title: "Longest Increasing Subsequence & Matrix Chain",
    track: "Advanced",
    dueDate: "Due Apr 6",
    status: "pending",
    totalSubmissions: 2,
    gradedCount: 0,
    maxScore: 100,
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: "sub-01",
    assignmentId: "asg-02",
    assignmentTitle: "Sliding Window Exercise",
    studentId: "std-002",
    studentName: "Elena Rostova",
    trackName: "Intermediate",
    submittedAt: "Today at 10:14 AM",
    status: "Awaiting Grading",
    maxScore: 100,
  },
  {
    id: "sub-02",
    assignmentId: "asg-02",
    assignmentTitle: "Sliding Window Exercise",
    studentId: "std-001",
    studentName: "Alex Morgan",
    trackName: "Intermediate",
    submittedAt: "Yesterday at 9:42 PM",
    status: "Awaiting Grading",
    maxScore: 100,
  },
  {
    id: "sub-03",
    assignmentId: "asg-02",
    assignmentTitle: "Sliding Window Exercise",
    studentId: "std-008",
    studentName: "David Kim",
    trackName: "Intermediate",
    submittedAt: "Yesterday at 6:15 PM",
    status: "Awaiting Grading",
    maxScore: 100,
  },
  {
    id: "sub-04",
    assignmentId: "asg-01",
    assignmentTitle: "Two Sum Practice & Frequency Arrays",
    studentId: "std-003",
    studentName: "Jordan Lee",
    trackName: "Intermediate",
    submittedAt: "Mar 26, 2026",
    status: "Graded",
    score: 88,
    maxScore: 100,
    feedback: "Solid edge case handling. Remember to optimize map lookups.",
  },
  {
    id: "sub-05",
    assignmentId: "asg-01",
    assignmentTitle: "Two Sum Practice & Frequency Arrays",
    studentId: "std-005",
    studentName: "Priya Sharma",
    trackName: "Foundations",
    submittedAt: "Mar 26, 2026",
    status: "Graded",
    score: 98,
    maxScore: 100,
    feedback: "Clean solution and great asymptotic analysis.",
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-01",
    title: "Sliding Window Live Code-Along & Breakout Rooms",
    track: "Intermediate",
    author: {
      name: "Sarah Jenkins",
      role: "Lead Instructor",
    },
    date: "Today at 9:00 AM",
    content:
      "For today's 6:00 PM session, please clone the starter repository and ensure your local Node or Python environment is ready. We will spend 45 minutes in pairs solving Variable Size window problems.",
    isPinned: true,
  },
  {
    id: "ann-02",
    title: "Cohort Mid-Point Check-in & One-on-One Office Hours",
    track: "All Tracks",
    author: {
      name: "Admin Operations",
      role: "Cohort Coordinator",
    },
    date: "Yesterday at 3:15 PM",
    content:
      "All students are encouraged to book a 15-minute sync with their track instructor this week to discuss interview readiness and progress.",
    isPinned: false,
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: "enr-01",
    studentName: "Alex Morgan",
    studentEmail: "alex.morgan@bootcamp.edu",
    trackName: "Intermediate",
    cohortName: "DSA Bootcamp 2026",
    enrolledDate: "Jan 12, 2026",
    status: "Active",
  },
  {
    id: "enr-02",
    studentName: "Elena Rostova",
    studentEmail: "elena.r@bootcamp.edu",
    trackName: "Intermediate",
    cohortName: "DSA Bootcamp 2026",
    enrolledDate: "Jan 12, 2026",
    status: "Active",
  },
  {
    id: "enr-03",
    studentName: "Tariq Mansour",
    studentEmail: "tariq.m@bootcamp.edu",
    trackName: "Foundations",
    cohortName: "DSA Bootcamp 2026",
    enrolledDate: "Jan 14, 2026",
    status: "Active",
  },
  {
    id: "enr-04",
    studentName: "Samantha Wright",
    studentEmail: "sam.wright@bootcamp.edu",
    trackName: "Advanced",
    cohortName: "DSA Bootcamp 2026",
    enrolledDate: "Jan 10, 2026",
    status: "Active",
  },
  {
    id: "enr-05",
    studentName: "Lucas Vance",
    studentEmail: "lucas.v@bootcamp.edu",
    trackName: "Foundations",
    cohortName: "DSA Bootcamp 2026",
    enrolledDate: "Feb 1, 2026",
    status: "Pending",
  },
];

export const mockActivityItems: ActivityItem[] = [
  {
    id: "act-01",
    type: "submission",
    description: "Elena Rostova submitted Sliding Window Exercise (Intermediate)",
    timestamp: "10 minutes ago",
  },
  {
    id: "act-02",
    type: "grade",
    description: "Sarah Jenkins graded Jordan Lee's Two Sum Practice (Score: 88/100)",
    timestamp: "1 hour ago",
  },
  {
    id: "act-03",
    type: "session",
    description: "Marcus Vance scheduled Arrays & Hash Maps workshop for tomorrow",
    timestamp: "3 hours ago",
  },
  {
    id: "act-04",
    type: "enrollment",
    description: "Lucas Vance applied for enrollment in Foundations Track",
    timestamp: "Yesterday",
  },
  {
    id: "act-05",
    type: "announcement",
    description: "Sarah Jenkins posted a pinned announcement in Intermediate track",
    timestamp: "Yesterday",
  },
];
